CREATE SCHEMA IF NOT EXISTS dna_memory;

DO $$
BEGIN
  CREATE TYPE dna_memory.memory_tier AS ENUM ('LONG_TERM', 'ARCHIVE', 'STAGING');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END;
$$;

DO $$
BEGIN
  CREATE TYPE dna_memory.memory_domain AS ENUM ('CONTEXTUAL', 'WORKING');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END;
$$;

DO $$
BEGIN
  CREATE TYPE dna_memory.memory_kind AS ENUM ('FACT', 'GRAPH_NODE', 'RULE', 'SOP_PATHWAY');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END;
$$;

CREATE TABLE IF NOT EXISTS dna_memory.central_memory (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  tenant_id TEXT NOT NULL,
  user_id TEXT NOT NULL,
  tier dna_memory.memory_tier NOT NULL,
  memory_domain dna_memory.memory_domain NOT NULL,
  memory_kind dna_memory.memory_kind NOT NULL,
  document_id TEXT NOT NULL,
  chunk_index INTEGER NOT NULL CHECK (chunk_index >= 0),
  token_count INTEGER NOT NULL CHECK (token_count >= 0),
  content TEXT NOT NULL,
  embedding vector(512) NOT NULL,
  metadata_jsonb JSONB NOT NULL DEFAULT '{}'::jsonb,
  schema_version TEXT NOT NULL,
  version INTEGER NOT NULL DEFAULT 1 CHECK (version > 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_accessed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT central_memory_pk PRIMARY KEY (tenant_id, user_id, id),
  CONSTRAINT central_memory_doc_chunk_unique UNIQUE (tenant_id, user_id, tier, document_id, chunk_index),
  CONSTRAINT central_memory_domain_kind_check CHECK (
    (
      memory_domain = 'CONTEXTUAL'::dna_memory.memory_domain
      AND memory_kind IN ('FACT'::dna_memory.memory_kind, 'GRAPH_NODE'::dna_memory.memory_kind)
    )
    OR
    (
      memory_domain = 'WORKING'::dna_memory.memory_domain
      AND memory_kind IN ('RULE'::dna_memory.memory_kind, 'SOP_PATHWAY'::dna_memory.memory_kind)
    )
  )
) PARTITION BY LIST (tenant_id);

CREATE TABLE IF NOT EXISTS dna_memory.central_memory_p_default
  PARTITION OF dna_memory.central_memory DEFAULT;

CREATE TABLE IF NOT EXISTS dna_memory.nodes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  label TEXT NOT NULL,
  properties_jsonb JSONB NOT NULL DEFAULT '{}'::jsonb,
  tenant_id TEXT NOT NULL,
  user_id TEXT NOT NULL,
  schema_version TEXT NOT NULL,
  version INTEGER NOT NULL DEFAULT 1 CHECK (version > 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT nodes_pk PRIMARY KEY (tenant_id, user_id, id)
) PARTITION BY LIST (tenant_id);

CREATE TABLE IF NOT EXISTS dna_memory.nodes_p_default
  PARTITION OF dna_memory.nodes DEFAULT;

CREATE TABLE IF NOT EXISTS dna_memory.edges (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  source_id BIGINT NOT NULL,
  target_id BIGINT NOT NULL,
  relationship_type TEXT NOT NULL,
  weight DOUBLE PRECISION NOT NULL DEFAULT 1 CHECK (weight >= 0),
  tenant_id TEXT NOT NULL,
  user_id TEXT NOT NULL,
  schema_version TEXT NOT NULL,
  version INTEGER NOT NULL DEFAULT 1 CHECK (version > 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT edges_pk PRIMARY KEY (tenant_id, user_id, id),
  CONSTRAINT edges_source_fk
    FOREIGN KEY (tenant_id, user_id, source_id)
    REFERENCES dna_memory.nodes (tenant_id, user_id, id)
    ON DELETE CASCADE,
  CONSTRAINT edges_target_fk
    FOREIGN KEY (tenant_id, user_id, target_id)
    REFERENCES dna_memory.nodes (tenant_id, user_id, id)
    ON DELETE CASCADE
) PARTITION BY LIST (tenant_id);

CREATE TABLE IF NOT EXISTS dna_memory.edges_p_default
  PARTITION OF dna_memory.edges DEFAULT;

CREATE OR REPLACE FUNCTION dna_memory.partition_suffix(p_tenant_id TEXT, p_user_id TEXT)
RETURNS TEXT
LANGUAGE SQL
IMMUTABLE
AS $$
  SELECT SUBSTRING(
    md5(lower(trim(COALESCE(p_tenant_id, ''))))
    FROM 1 FOR 20
  );
$$;

CREATE OR REPLACE FUNCTION dna_memory.ensure_vector_index(p_index_name TEXT, p_table REGCLASS)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
  BEGIN
    EXECUTE format(
      'CREATE INDEX IF NOT EXISTS %I ON %s USING hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 64)',
      p_index_name,
      p_table
    );
  EXCEPTION
    WHEN undefined_object OR feature_not_supported THEN
      EXECUTE format(
        'CREATE INDEX IF NOT EXISTS %I ON %s USING ivfflat (embedding vector_cosine_ops) WITH (lists = 64)',
        p_index_name,
        p_table
      );
  END;
END;
$$;

CREATE OR REPLACE FUNCTION dna_memory.ensure_partition_for_subject(
  p_tenant_id TEXT,
  p_user_id TEXT
)
RETURNS TABLE (central_partition TEXT, nodes_partition TEXT, edges_partition TEXT)
LANGUAGE plpgsql
AS $$
DECLARE
  suffix TEXT;
  central_name TEXT;
  nodes_name TEXT;
  edges_name TEXT;
BEGIN
  IF trim(COALESCE(p_tenant_id, '')) = '' OR trim(COALESCE(p_user_id, '')) = '' THEN
    RAISE EXCEPTION 'tenant_id and user_id must be non-empty for partition provisioning';
  END IF;

  suffix := dna_memory.partition_suffix(p_tenant_id, p_user_id);
  central_name := format('central_memory_p_%s', suffix);
  nodes_name := format('nodes_p_%s', suffix);
  edges_name := format('edges_p_%s', suffix);

  IF to_regclass(format('dna_memory.%I', central_name)) IS NULL THEN
    EXECUTE format(
      'CREATE TABLE dna_memory.%I PARTITION OF dna_memory.central_memory FOR VALUES IN (%L)',
      central_name,
      p_tenant_id
    );
  END IF;

  IF to_regclass(format('dna_memory.%I', nodes_name)) IS NULL THEN
    EXECUTE format(
      'CREATE TABLE dna_memory.%I PARTITION OF dna_memory.nodes FOR VALUES IN (%L)',
      nodes_name,
      p_tenant_id
    );
  END IF;

  IF to_regclass(format('dna_memory.%I', edges_name)) IS NULL THEN
    EXECUTE format(
      'CREATE TABLE dna_memory.%I PARTITION OF dna_memory.edges FOR VALUES IN (%L)',
      edges_name,
      p_tenant_id
    );
  END IF;

  PERFORM dna_memory.ensure_vector_index(
    format('%s_embedding_idx', central_name),
    format('dna_memory.%I', central_name)::regclass
  );

  EXECUTE format(
    'CREATE INDEX IF NOT EXISTS %I ON dna_memory.%I (tier, memory_domain, updated_at DESC)',
    format('%s_tier_domain_updated_idx', central_name),
    central_name
  );

  EXECUTE format(
    'CREATE INDEX IF NOT EXISTS %I ON dna_memory.%I (document_id, chunk_index)',
    format('%s_doc_chunk_idx', central_name),
    central_name
  );

  EXECUTE format(
    'CREATE INDEX IF NOT EXISTS %I ON dna_memory.%I (label)',
    format('%s_label_idx', nodes_name),
    nodes_name
  );

  EXECUTE format(
    'CREATE INDEX IF NOT EXISTS %I ON dna_memory.%I (source_id, relationship_type, weight DESC)',
    format('%s_source_rel_idx', edges_name),
    edges_name
  );

  EXECUTE format(
    'CREATE INDEX IF NOT EXISTS %I ON dna_memory.%I (target_id)',
    format('%s_target_idx', edges_name),
    edges_name
  );

  RETURN QUERY SELECT central_name, nodes_name, edges_name;
END;
$$;

CREATE OR REPLACE FUNCTION dna_memory.touch_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at := NOW();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_central_memory_touch_updated_at ON dna_memory.central_memory;
CREATE TRIGGER trg_central_memory_touch_updated_at
BEFORE UPDATE ON dna_memory.central_memory
FOR EACH ROW
EXECUTE FUNCTION dna_memory.touch_updated_at();

DROP TRIGGER IF EXISTS trg_nodes_touch_updated_at ON dna_memory.nodes;
CREATE TRIGGER trg_nodes_touch_updated_at
BEFORE UPDATE ON dna_memory.nodes
FOR EACH ROW
EXECUTE FUNCTION dna_memory.touch_updated_at();

DROP TRIGGER IF EXISTS trg_edges_touch_updated_at ON dna_memory.edges;
CREATE TRIGGER trg_edges_touch_updated_at
BEFORE UPDATE ON dna_memory.edges
FOR EACH ROW
EXECUTE FUNCTION dna_memory.touch_updated_at();

ALTER TABLE dna_memory.central_memory ENABLE ROW LEVEL SECURITY;
ALTER TABLE dna_memory.nodes ENABLE ROW LEVEL SECURITY;
ALTER TABLE dna_memory.edges ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS central_memory_isolation ON dna_memory.central_memory;
CREATE POLICY central_memory_isolation
ON dna_memory.central_memory
USING (
  tenant_id = current_setting('app.tenant_id', true)
  AND user_id = current_setting('app.user_id', true)
)
WITH CHECK (
  tenant_id = current_setting('app.tenant_id', true)
  AND user_id = current_setting('app.user_id', true)
);

DROP POLICY IF EXISTS nodes_isolation ON dna_memory.nodes;
CREATE POLICY nodes_isolation
ON dna_memory.nodes
USING (
  tenant_id = current_setting('app.tenant_id', true)
  AND user_id = current_setting('app.user_id', true)
)
WITH CHECK (
  tenant_id = current_setting('app.tenant_id', true)
  AND user_id = current_setting('app.user_id', true)
);

DROP POLICY IF EXISTS edges_isolation ON dna_memory.edges;
CREATE POLICY edges_isolation
ON dna_memory.edges
USING (
  tenant_id = current_setting('app.tenant_id', true)
  AND user_id = current_setting('app.user_id', true)
)
WITH CHECK (
  tenant_id = current_setting('app.tenant_id', true)
  AND user_id = current_setting('app.user_id', true)
);

CREATE INDEX IF NOT EXISTS central_memory_default_tier_domain_updated_idx
  ON dna_memory.central_memory_p_default (tier, memory_domain, updated_at DESC);
CREATE INDEX IF NOT EXISTS central_memory_default_doc_chunk_idx
  ON dna_memory.central_memory_p_default (document_id, chunk_index);
SELECT dna_memory.ensure_vector_index(
  'central_memory_default_embedding_idx',
  'dna_memory.central_memory_p_default'::regclass
);

CREATE INDEX IF NOT EXISTS nodes_default_label_idx ON dna_memory.nodes_p_default (label);
CREATE INDEX IF NOT EXISTS edges_default_source_rel_idx
  ON dna_memory.edges_p_default (source_id, relationship_type, weight DESC);
CREATE INDEX IF NOT EXISTS edges_default_target_idx ON dna_memory.edges_p_default (target_id);

CREATE OR REPLACE FUNCTION dna_memory.set_rls_context(
  p_tenant_id TEXT,
  p_user_id TEXT
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
  PERFORM set_config('app.tenant_id', p_tenant_id, true);
  PERFORM set_config('app.user_id', p_user_id, true);
END;
$$;

CREATE OR REPLACE FUNCTION dna_memory.update_central_memory_occ(
  p_tenant_id TEXT,
  p_user_id TEXT,
  p_id BIGINT,
  p_expected_version INTEGER,
  p_content TEXT DEFAULT NULL,
  p_metadata_jsonb JSONB DEFAULT NULL,
  p_token_count INTEGER DEFAULT NULL,
  p_last_accessed_at TIMESTAMPTZ DEFAULT NULL
)
RETURNS TABLE (applied BOOLEAN, new_version INTEGER)
LANGUAGE plpgsql
AS $$
DECLARE
  v_next_version INTEGER;
BEGIN
  UPDATE dna_memory.central_memory
  SET
    content = COALESCE(p_content, content),
    metadata_jsonb = COALESCE(p_metadata_jsonb, metadata_jsonb),
    token_count = COALESCE(p_token_count, token_count),
    last_accessed_at = COALESCE(p_last_accessed_at, last_accessed_at),
    version = version + 1,
    updated_at = NOW()
  WHERE tenant_id = p_tenant_id
    AND user_id = p_user_id
    AND id = p_id
    AND version = p_expected_version
  RETURNING version INTO v_next_version;

  IF v_next_version IS NULL THEN
    RETURN QUERY SELECT FALSE, NULL::INTEGER;
  ELSE
    RETURN QUERY SELECT TRUE, v_next_version;
  END IF;
END;
$$;

CREATE OR REPLACE FUNCTION dna_memory.traverse_graph(
  p_tenant_id TEXT,
  p_user_id TEXT,
  p_start_node_id BIGINT,
  p_max_depth INTEGER DEFAULT 3
)
RETURNS TABLE (
  depth INTEGER,
  source_id BIGINT,
  target_id BIGINT,
  relationship_type TEXT,
  weight DOUBLE PRECISION,
  path BIGINT[]
)
LANGUAGE SQL
STABLE
AS $$
  WITH RECURSIVE walk AS (
    SELECT
      1 AS depth,
      e.source_id,
      e.target_id,
      e.relationship_type,
      e.weight,
      ARRAY[e.source_id, e.target_id]::BIGINT[] AS path
    FROM dna_memory.edges e
    WHERE e.tenant_id = p_tenant_id
      AND e.user_id = p_user_id
      AND e.source_id = p_start_node_id

    UNION ALL

    SELECT
      walk.depth + 1,
      e.source_id,
      e.target_id,
      e.relationship_type,
      e.weight,
      walk.path || e.target_id
    FROM walk
    JOIN dna_memory.edges e
      ON e.tenant_id = p_tenant_id
      AND e.user_id = p_user_id
      AND e.source_id = walk.target_id
    WHERE walk.depth < GREATEST(1, p_max_depth)
      AND NOT (e.target_id = ANY(walk.path))
  )
  SELECT depth, source_id, target_id, relationship_type, weight, path
  FROM walk
  ORDER BY depth ASC, weight DESC;
$$;

CREATE OR REPLACE VIEW dna_memory.long_term_strand AS
SELECT *
FROM dna_memory.central_memory
WHERE tier = 'LONG_TERM'::dna_memory.memory_tier;

CREATE OR REPLACE VIEW dna_memory.archive_strand AS
SELECT *
FROM dna_memory.central_memory
WHERE tier = 'ARCHIVE'::dna_memory.memory_tier;

CREATE OR REPLACE VIEW dna_memory.staging_strand AS
SELECT *
FROM dna_memory.central_memory
WHERE tier = 'STAGING'::dna_memory.memory_tier;

CREATE OR REPLACE VIEW dna_memory.contextual_memory AS
SELECT *
FROM dna_memory.central_memory
WHERE memory_domain = 'CONTEXTUAL'::dna_memory.memory_domain;

CREATE OR REPLACE VIEW dna_memory.working_memory AS
SELECT *
FROM dna_memory.central_memory
WHERE memory_domain = 'WORKING'::dna_memory.memory_domain;
