CREATE EXTENSION IF NOT EXISTS pgcrypto;

DO $$
BEGIN
  CREATE TYPE dna_memory.phase4_quarantine_action AS ENUM ('APPROVE', 'REJECT');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END;
$$;

CREATE TABLE IF NOT EXISTS dna_memory.admin_json_configs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  config_id UUID NOT NULL DEFAULT gen_random_uuid(),
  tenant_id TEXT NOT NULL,
  user_id TEXT NOT NULL,
  config_key TEXT NOT NULL,
  config_jsonb JSONB NOT NULL DEFAULT '{}'::jsonb,
  schema_version TEXT NOT NULL,
  version INTEGER NOT NULL DEFAULT 1 CHECK (version > 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT admin_json_configs_pk PRIMARY KEY (tenant_id, user_id, id),
  CONSTRAINT admin_json_configs_config_unique UNIQUE (tenant_id, user_id, config_key),
  CONSTRAINT admin_json_configs_config_id_unique UNIQUE (tenant_id, user_id, config_id)
) PARTITION BY LIST (tenant_id);

CREATE TABLE IF NOT EXISTS dna_memory.admin_json_configs_p_default
  PARTITION OF dna_memory.admin_json_configs DEFAULT;

CREATE TABLE IF NOT EXISTS dna_memory.pgvector_backups (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  backup_id UUID NOT NULL DEFAULT gen_random_uuid(),
  tenant_id TEXT NOT NULL,
  user_id TEXT NOT NULL,
  backup_label TEXT NOT NULL,
  backup_payload_jsonb JSONB NOT NULL DEFAULT '{}'::jsonb,
  row_count INTEGER NOT NULL DEFAULT 0 CHECK (row_count >= 0),
  metadata_jsonb JSONB NOT NULL DEFAULT '{}'::jsonb,
  schema_version TEXT NOT NULL,
  version INTEGER NOT NULL DEFAULT 1 CHECK (version > 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT pgvector_backups_pk PRIMARY KEY (tenant_id, user_id, id),
  CONSTRAINT pgvector_backups_backup_id_unique UNIQUE (tenant_id, user_id, backup_id)
) PARTITION BY LIST (tenant_id);

CREATE TABLE IF NOT EXISTS dna_memory.pgvector_backups_p_default
  PARTITION OF dna_memory.pgvector_backups DEFAULT;

CREATE TABLE IF NOT EXISTS dna_memory.quarantine_reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  tenant_id TEXT NOT NULL,
  user_id TEXT NOT NULL,
  memory_id BIGINT NOT NULL,
  diff_event_id BIGINT,
  action dna_memory.phase4_quarantine_action NOT NULL,
  review_note TEXT,
  reviewer_user_id TEXT NOT NULL,
  schema_version TEXT NOT NULL,
  version INTEGER NOT NULL DEFAULT 1 CHECK (version > 0),
  metadata_jsonb JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT quarantine_reviews_pk PRIMARY KEY (tenant_id, user_id, id),
  CONSTRAINT quarantine_reviews_memory_fk
    FOREIGN KEY (tenant_id, user_id, memory_id)
    REFERENCES dna_memory.central_memory (tenant_id, user_id, id)
    ON DELETE CASCADE
) PARTITION BY LIST (tenant_id);

CREATE TABLE IF NOT EXISTS dna_memory.quarantine_reviews_p_default
  PARTITION OF dna_memory.quarantine_reviews DEFAULT;

CREATE INDEX IF NOT EXISTS admin_json_configs_default_key_idx
  ON dna_memory.admin_json_configs_p_default (config_key, updated_at DESC);

CREATE INDEX IF NOT EXISTS pgvector_backups_default_created_idx
  ON dna_memory.pgvector_backups_p_default (created_at DESC);

CREATE INDEX IF NOT EXISTS quarantine_reviews_default_memory_idx
  ON dna_memory.quarantine_reviews_p_default (memory_id, created_at DESC);
CREATE INDEX IF NOT EXISTS quarantine_reviews_default_action_idx
  ON dna_memory.quarantine_reviews_p_default (action, created_at DESC);

DROP TRIGGER IF EXISTS trg_admin_json_configs_touch_updated_at ON dna_memory.admin_json_configs;
CREATE TRIGGER trg_admin_json_configs_touch_updated_at
BEFORE UPDATE ON dna_memory.admin_json_configs
FOR EACH ROW
EXECUTE FUNCTION dna_memory.touch_updated_at();

DROP TRIGGER IF EXISTS trg_pgvector_backups_touch_updated_at ON dna_memory.pgvector_backups;
CREATE TRIGGER trg_pgvector_backups_touch_updated_at
BEFORE UPDATE ON dna_memory.pgvector_backups
FOR EACH ROW
EXECUTE FUNCTION dna_memory.touch_updated_at();

DROP TRIGGER IF EXISTS trg_quarantine_reviews_touch_updated_at ON dna_memory.quarantine_reviews;
CREATE TRIGGER trg_quarantine_reviews_touch_updated_at
BEFORE UPDATE ON dna_memory.quarantine_reviews
FOR EACH ROW
EXECUTE FUNCTION dna_memory.touch_updated_at();

ALTER TABLE dna_memory.admin_json_configs ENABLE ROW LEVEL SECURITY;
ALTER TABLE dna_memory.pgvector_backups ENABLE ROW LEVEL SECURITY;
ALTER TABLE dna_memory.quarantine_reviews ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS admin_json_configs_isolation ON dna_memory.admin_json_configs;
CREATE POLICY admin_json_configs_isolation
ON dna_memory.admin_json_configs
USING (
  tenant_id = current_setting('app.tenant_id', true)
  AND user_id = current_setting('app.user_id', true)
)
WITH CHECK (
  tenant_id = current_setting('app.tenant_id', true)
  AND user_id = current_setting('app.user_id', true)
);

DROP POLICY IF EXISTS pgvector_backups_isolation ON dna_memory.pgvector_backups;
CREATE POLICY pgvector_backups_isolation
ON dna_memory.pgvector_backups
USING (
  tenant_id = current_setting('app.tenant_id', true)
  AND user_id = current_setting('app.user_id', true)
)
WITH CHECK (
  tenant_id = current_setting('app.tenant_id', true)
  AND user_id = current_setting('app.user_id', true)
);

DROP POLICY IF EXISTS quarantine_reviews_isolation ON dna_memory.quarantine_reviews;
CREATE POLICY quarantine_reviews_isolation
ON dna_memory.quarantine_reviews
USING (
  tenant_id = current_setting('app.tenant_id', true)
  AND user_id = current_setting('app.user_id', true)
)
WITH CHECK (
  tenant_id = current_setting('app.tenant_id', true)
  AND user_id = current_setting('app.user_id', true)
);

CREATE OR REPLACE FUNCTION dna_memory.ensure_phase4_partition_for_subject(
  p_tenant_id TEXT,
  p_user_id TEXT
)
RETURNS TABLE (
  config_partition TEXT,
  backup_partition TEXT,
  review_partition TEXT
)
LANGUAGE plpgsql
AS $$
DECLARE
  suffix TEXT;
  config_name TEXT;
  backup_name TEXT;
  review_name TEXT;
BEGIN
  IF trim(COALESCE(p_tenant_id, '')) = '' OR trim(COALESCE(p_user_id, '')) = '' THEN
    RAISE EXCEPTION 'tenant_id and user_id must be non-empty for phase4 partition provisioning';
  END IF;

  suffix := dna_memory.partition_suffix(p_tenant_id, p_user_id);
  config_name := format('admin_json_configs_p_%s', suffix);
  backup_name := format('pgvector_backups_p_%s', suffix);
  review_name := format('quarantine_reviews_p_%s', suffix);

  IF to_regclass(format('dna_memory.%I', config_name)) IS NULL THEN
    EXECUTE format(
      'CREATE TABLE dna_memory.%I PARTITION OF dna_memory.admin_json_configs FOR VALUES IN (%L)',
      config_name,
      p_tenant_id
    );
  END IF;

  IF to_regclass(format('dna_memory.%I', backup_name)) IS NULL THEN
    EXECUTE format(
      'CREATE TABLE dna_memory.%I PARTITION OF dna_memory.pgvector_backups FOR VALUES IN (%L)',
      backup_name,
      p_tenant_id
    );
  END IF;

  IF to_regclass(format('dna_memory.%I', review_name)) IS NULL THEN
    EXECUTE format(
      'CREATE TABLE dna_memory.%I PARTITION OF dna_memory.quarantine_reviews FOR VALUES IN (%L)',
      review_name,
      p_tenant_id
    );
  END IF;

  EXECUTE format(
    'CREATE INDEX IF NOT EXISTS %I ON dna_memory.%I (config_key, updated_at DESC)',
    format('%s_key_updated_idx', config_name),
    config_name
  );

  EXECUTE format(
    'CREATE INDEX IF NOT EXISTS %I ON dna_memory.%I (created_at DESC)',
    format('%s_created_idx', backup_name),
    backup_name
  );

  EXECUTE format(
    'CREATE INDEX IF NOT EXISTS %I ON dna_memory.%I (memory_id, created_at DESC)',
    format('%s_memory_created_idx', review_name),
    review_name
  );

  RETURN QUERY SELECT config_name, backup_name, review_name;
END;
$$;

CREATE OR REPLACE FUNCTION dna_memory.update_admin_json_config_occ(
  p_tenant_id TEXT,
  p_user_id TEXT,
  p_id BIGINT,
  p_expected_version INTEGER,
  p_config_jsonb JSONB
)
RETURNS TABLE (applied BOOLEAN, new_version INTEGER)
LANGUAGE plpgsql
AS $$
DECLARE
  v_next_version INTEGER;
BEGIN
  UPDATE dna_memory.admin_json_configs
  SET
    config_jsonb = p_config_jsonb,
    version = version + 1,
    updated_at = NOW()
  WHERE tenant_id = p_tenant_id
    AND user_id = p_user_id
    AND id = p_id
    AND version = p_expected_version
  RETURNING version INTO v_next_version;

  IF v_next_version IS NULL THEN
    RETURN QUERY SELECT FALSE, NULL::INTEGER;
  ELSE
    RETURN QUERY SELECT TRUE, v_next_version;
  END IF;
END;
$$;

CREATE OR REPLACE VIEW dna_memory.phase4_quarantine_overview AS
SELECT
  cm.tenant_id,
  cm.user_id,
  COUNT(*)::bigint AS pending_items,
  MAX(cm.updated_at) AS newest_item_at
FROM dna_memory.central_memory cm
LEFT JOIN dna_memory.quarantine_reviews qr
  ON qr.tenant_id = cm.tenant_id
  AND qr.user_id = cm.user_id
  AND qr.memory_id = cm.id
WHERE cm.tier = 'STAGING'::dna_memory.memory_tier
  AND qr.id IS NULL
GROUP BY cm.tenant_id, cm.user_id;
