CREATE EXTENSION IF NOT EXISTS pgcrypto;

DO $$
BEGIN
  CREATE TYPE dna_memory.pathway_status AS ENUM ('ACTIVE', 'DEPRECATED');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END;
$$;

DO $$
BEGIN
  CREATE TYPE dna_memory.blackboard_status AS ENUM ('ACTIVE', 'COMPLETED', 'FAILED', 'CANCELLED');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END;
$$;

DO $$
BEGIN
  CREATE TYPE dna_memory.blackboard_step_status AS ENUM ('PENDING', 'CLAIMED', 'IN_PROGRESS', 'COMPLETED', 'SKIPPED');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END;
$$;

CREATE TABLE IF NOT EXISTS dna_memory.pathway_registry (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  pathway_id UUID NOT NULL DEFAULT gen_random_uuid(),
  tenant_id TEXT NOT NULL,
  user_id TEXT NOT NULL,
  pathway_name TEXT NOT NULL,
  pathway_jsonb JSONB NOT NULL DEFAULT '{}'::jsonb,
  pathway_hash TEXT NOT NULL,
  status dna_memory.pathway_status NOT NULL DEFAULT 'ACTIVE',
  overrides_pathway_id UUID,
  schema_version TEXT NOT NULL,
  version INTEGER NOT NULL DEFAULT 1 CHECK (version > 0),
  metadata_jsonb JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT pathway_registry_pk PRIMARY KEY (tenant_id, user_id, id),
  CONSTRAINT pathway_registry_pathway_unique UNIQUE (tenant_id, user_id, pathway_id)
) PARTITION BY LIST (tenant_id);

CREATE TABLE IF NOT EXISTS dna_memory.pathway_registry_p_default
  PARTITION OF dna_memory.pathway_registry DEFAULT;

CREATE TABLE IF NOT EXISTS dna_memory.blackboard_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  board_id UUID NOT NULL DEFAULT gen_random_uuid(),
  tenant_id TEXT NOT NULL,
  user_id TEXT NOT NULL,
  pathway_id UUID,
  session_id TEXT NOT NULL,
  flow_id TEXT,
  main_agent_id TEXT,
  status dna_memory.blackboard_status NOT NULL DEFAULT 'ACTIVE',
  payload_jsonb JSONB NOT NULL DEFAULT '{}'::jsonb,
  schema_version TEXT NOT NULL,
  version INTEGER NOT NULL DEFAULT 1 CHECK (version > 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT blackboard_sessions_pk PRIMARY KEY (tenant_id, user_id, id),
  CONSTRAINT blackboard_sessions_board_unique UNIQUE (tenant_id, user_id, board_id),
  CONSTRAINT blackboard_sessions_pathway_fk
    FOREIGN KEY (tenant_id, user_id, pathway_id)
    REFERENCES dna_memory.pathway_registry (tenant_id, user_id, pathway_id)
    ON DELETE SET NULL
) PARTITION BY LIST (tenant_id);

CREATE TABLE IF NOT EXISTS dna_memory.blackboard_sessions_p_default
  PARTITION OF dna_memory.blackboard_sessions DEFAULT;

CREATE TABLE IF NOT EXISTS dna_memory.blackboard_steps (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  tenant_id TEXT NOT NULL,
  user_id TEXT NOT NULL,
  board_id UUID NOT NULL,
  pathway_id UUID,
  step_key TEXT NOT NULL,
  step_order INTEGER NOT NULL CHECK (step_order >= 0),
  step_payload_jsonb JSONB NOT NULL DEFAULT '{}'::jsonb,
  status dna_memory.blackboard_step_status NOT NULL DEFAULT 'PENDING',
  claimed_by_agent_id TEXT,
  lock_token TEXT,
  lock_expires_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  result_jsonb JSONB NOT NULL DEFAULT '{}'::jsonb,
  schema_version TEXT NOT NULL,
  version INTEGER NOT NULL DEFAULT 1 CHECK (version > 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT blackboard_steps_pk PRIMARY KEY (tenant_id, user_id, id),
  CONSTRAINT blackboard_steps_unique_step UNIQUE (tenant_id, user_id, board_id, step_key),
  CONSTRAINT blackboard_steps_board_fk
    FOREIGN KEY (tenant_id, user_id, board_id)
    REFERENCES dna_memory.blackboard_sessions (tenant_id, user_id, board_id)
    ON DELETE CASCADE,
  CONSTRAINT blackboard_steps_pathway_fk
    FOREIGN KEY (tenant_id, user_id, pathway_id)
    REFERENCES dna_memory.pathway_registry (tenant_id, user_id, pathway_id)
    ON DELETE SET NULL
) PARTITION BY LIST (tenant_id);

CREATE TABLE IF NOT EXISTS dna_memory.blackboard_steps_p_default
  PARTITION OF dna_memory.blackboard_steps DEFAULT;

CREATE TABLE IF NOT EXISTS dna_memory.dna_sync_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  event_id UUID NOT NULL DEFAULT gen_random_uuid(),
  tenant_id TEXT NOT NULL,
  user_id TEXT NOT NULL,
  channel TEXT NOT NULL,
  event_type TEXT NOT NULL,
  payload_jsonb JSONB NOT NULL DEFAULT '{}'::jsonb,
  published_to_redis BOOLEAN NOT NULL DEFAULT FALSE,
  schema_version TEXT NOT NULL,
  version INTEGER NOT NULL DEFAULT 1 CHECK (version > 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT dna_sync_events_pk PRIMARY KEY (tenant_id, user_id, id),
  CONSTRAINT dna_sync_events_event_unique UNIQUE (tenant_id, user_id, event_id)
) PARTITION BY LIST (tenant_id);

CREATE TABLE IF NOT EXISTS dna_memory.dna_sync_events_p_default
  PARTITION OF dna_memory.dna_sync_events DEFAULT;

CREATE INDEX IF NOT EXISTS pathway_registry_default_status_idx
  ON dna_memory.pathway_registry_p_default (status, pathway_name);
CREATE INDEX IF NOT EXISTS pathway_registry_default_updated_idx
  ON dna_memory.pathway_registry_p_default (updated_at DESC);

CREATE INDEX IF NOT EXISTS blackboard_sessions_default_status_idx
  ON dna_memory.blackboard_sessions_p_default (status, created_at DESC);
CREATE INDEX IF NOT EXISTS blackboard_sessions_default_session_idx
  ON dna_memory.blackboard_sessions_p_default (session_id, created_at DESC);

CREATE INDEX IF NOT EXISTS blackboard_steps_default_status_order_idx
  ON dna_memory.blackboard_steps_p_default (status, step_order ASC);
CREATE INDEX IF NOT EXISTS blackboard_steps_default_board_idx
  ON dna_memory.blackboard_steps_p_default (board_id, step_order ASC);
CREATE INDEX IF NOT EXISTS blackboard_steps_default_lock_idx
  ON dna_memory.blackboard_steps_p_default (lock_expires_at);

CREATE INDEX IF NOT EXISTS dna_sync_events_default_created_idx
  ON dna_memory.dna_sync_events_p_default (created_at DESC);
CREATE INDEX IF NOT EXISTS dna_sync_events_default_type_idx
  ON dna_memory.dna_sync_events_p_default (event_type, created_at DESC);

DROP TRIGGER IF EXISTS trg_pathway_registry_touch_updated_at ON dna_memory.pathway_registry;
CREATE TRIGGER trg_pathway_registry_touch_updated_at
BEFORE UPDATE ON dna_memory.pathway_registry
FOR EACH ROW
EXECUTE FUNCTION dna_memory.touch_updated_at();

DROP TRIGGER IF EXISTS trg_blackboard_sessions_touch_updated_at ON dna_memory.blackboard_sessions;
CREATE TRIGGER trg_blackboard_sessions_touch_updated_at
BEFORE UPDATE ON dna_memory.blackboard_sessions
FOR EACH ROW
EXECUTE FUNCTION dna_memory.touch_updated_at();

DROP TRIGGER IF EXISTS trg_blackboard_steps_touch_updated_at ON dna_memory.blackboard_steps;
CREATE TRIGGER trg_blackboard_steps_touch_updated_at
BEFORE UPDATE ON dna_memory.blackboard_steps
FOR EACH ROW
EXECUTE FUNCTION dna_memory.touch_updated_at();

DROP TRIGGER IF EXISTS trg_dna_sync_events_touch_updated_at ON dna_memory.dna_sync_events;
CREATE TRIGGER trg_dna_sync_events_touch_updated_at
BEFORE UPDATE ON dna_memory.dna_sync_events
FOR EACH ROW
EXECUTE FUNCTION dna_memory.touch_updated_at();

ALTER TABLE dna_memory.pathway_registry ENABLE ROW LEVEL SECURITY;
ALTER TABLE dna_memory.blackboard_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE dna_memory.blackboard_steps ENABLE ROW LEVEL SECURITY;
ALTER TABLE dna_memory.dna_sync_events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS pathway_registry_isolation ON dna_memory.pathway_registry;
CREATE POLICY pathway_registry_isolation
ON dna_memory.pathway_registry
USING (
  tenant_id = current_setting('app.tenant_id', true)
  AND user_id = current_setting('app.user_id', true)
)
WITH CHECK (
  tenant_id = current_setting('app.tenant_id', true)
  AND user_id = current_setting('app.user_id', true)
);

DROP POLICY IF EXISTS blackboard_sessions_isolation ON dna_memory.blackboard_sessions;
CREATE POLICY blackboard_sessions_isolation
ON dna_memory.blackboard_sessions
USING (
  tenant_id = current_setting('app.tenant_id', true)
  AND user_id = current_setting('app.user_id', true)
)
WITH CHECK (
  tenant_id = current_setting('app.tenant_id', true)
  AND user_id = current_setting('app.user_id', true)
);

DROP POLICY IF EXISTS blackboard_steps_isolation ON dna_memory.blackboard_steps;
CREATE POLICY blackboard_steps_isolation
ON dna_memory.blackboard_steps
USING (
  tenant_id = current_setting('app.tenant_id', true)
  AND user_id = current_setting('app.user_id', true)
)
WITH CHECK (
  tenant_id = current_setting('app.tenant_id', true)
  AND user_id = current_setting('app.user_id', true)
);

DROP POLICY IF EXISTS dna_sync_events_isolation ON dna_memory.dna_sync_events;
CREATE POLICY dna_sync_events_isolation
ON dna_memory.dna_sync_events
USING (
  tenant_id = current_setting('app.tenant_id', true)
  AND user_id = current_setting('app.user_id', true)
)
WITH CHECK (
  tenant_id = current_setting('app.tenant_id', true)
  AND user_id = current_setting('app.user_id', true)
);

CREATE OR REPLACE FUNCTION dna_memory.ensure_phase3_partition_for_subject(
  p_tenant_id TEXT,
  p_user_id TEXT
)
RETURNS TABLE (
  pathway_partition TEXT,
  board_partition TEXT,
  step_partition TEXT,
  sync_partition TEXT
)
LANGUAGE plpgsql
AS $$
DECLARE
  suffix TEXT;
  pathway_name TEXT;
  board_name TEXT;
  step_name TEXT;
  sync_name TEXT;
BEGIN
  IF trim(COALESCE(p_tenant_id, '')) = '' OR trim(COALESCE(p_user_id, '')) = '' THEN
    RAISE EXCEPTION 'tenant_id and user_id must be non-empty for phase3 partition provisioning';
  END IF;

  suffix := dna_memory.partition_suffix(p_tenant_id, p_user_id);
  pathway_name := format('pathway_registry_p_%s', suffix);
  board_name := format('blackboard_sessions_p_%s', suffix);
  step_name := format('blackboard_steps_p_%s', suffix);
  sync_name := format('dna_sync_events_p_%s', suffix);

  IF to_regclass(format('dna_memory.%I', pathway_name)) IS NULL THEN
    EXECUTE format(
      'CREATE TABLE dna_memory.%I PARTITION OF dna_memory.pathway_registry FOR VALUES IN (%L)',
      pathway_name,
      p_tenant_id
    );
  END IF;

  IF to_regclass(format('dna_memory.%I', board_name)) IS NULL THEN
    EXECUTE format(
      'CREATE TABLE dna_memory.%I PARTITION OF dna_memory.blackboard_sessions FOR VALUES IN (%L)',
      board_name,
      p_tenant_id
    );
  END IF;

  IF to_regclass(format('dna_memory.%I', step_name)) IS NULL THEN
    EXECUTE format(
      'CREATE TABLE dna_memory.%I PARTITION OF dna_memory.blackboard_steps FOR VALUES IN (%L)',
      step_name,
      p_tenant_id
    );
  END IF;

  IF to_regclass(format('dna_memory.%I', sync_name)) IS NULL THEN
    EXECUTE format(
      'CREATE TABLE dna_memory.%I PARTITION OF dna_memory.dna_sync_events FOR VALUES IN (%L)',
      sync_name,
      p_tenant_id
    );
  END IF;

  EXECUTE format(
    'CREATE INDEX IF NOT EXISTS %I ON dna_memory.%I (status, pathway_name)',
    format('%s_status_name_idx', pathway_name),
    pathway_name
  );

  EXECUTE format(
    'CREATE INDEX IF NOT EXISTS %I ON dna_memory.%I (status, created_at DESC)',
    format('%s_status_created_idx', board_name),
    board_name
  );

  EXECUTE format(
    'CREATE INDEX IF NOT EXISTS %I ON dna_memory.%I (board_id, step_order ASC)',
    format('%s_board_order_idx', step_name),
    step_name
  );

  EXECUTE format(
    'CREATE INDEX IF NOT EXISTS %I ON dna_memory.%I (event_type, created_at DESC)',
    format('%s_event_created_idx', sync_name),
    sync_name
  );

  RETURN QUERY SELECT pathway_name, board_name, step_name, sync_name;
END;
$$;

CREATE OR REPLACE FUNCTION dna_memory.update_pathway_registry_occ(
  p_tenant_id TEXT,
  p_user_id TEXT,
  p_id BIGINT,
  p_expected_version INTEGER,
  p_pathway_jsonb JSONB DEFAULT NULL,
  p_status dna_memory.pathway_status DEFAULT NULL,
  p_metadata_jsonb JSONB DEFAULT NULL,
  p_overrides_pathway_id UUID DEFAULT NULL
)
RETURNS TABLE (applied BOOLEAN, new_version INTEGER)
LANGUAGE plpgsql
AS $$
DECLARE
  v_next_version INTEGER;
BEGIN
  UPDATE dna_memory.pathway_registry
  SET
    pathway_jsonb = COALESCE(p_pathway_jsonb, pathway_jsonb),
    status = COALESCE(p_status, status),
    metadata_jsonb = COALESCE(p_metadata_jsonb, metadata_jsonb),
    overrides_pathway_id = COALESCE(p_overrides_pathway_id, overrides_pathway_id),
    version = version + 1,
    updated_at = NOW()
  WHERE tenant_id = p_tenant_id
    AND user_id = p_user_id
    AND id = p_id
    AND version = p_expected_version
  RETURNING version INTO v_next_version;

  IF v_next_version IS NULL THEN
    RETURN QUERY SELECT FALSE, NULL::INTEGER;
  ELSE
    RETURN QUERY SELECT TRUE, v_next_version;
  END IF;
END;
$$;

CREATE OR REPLACE FUNCTION dna_memory.update_blackboard_step_occ(
  p_tenant_id TEXT,
  p_user_id TEXT,
  p_id BIGINT,
  p_expected_version INTEGER,
  p_status dna_memory.blackboard_step_status DEFAULT NULL,
  p_claimed_by_agent_id TEXT DEFAULT NULL,
  p_lock_token TEXT DEFAULT NULL,
  p_lock_expires_at TIMESTAMPTZ DEFAULT NULL,
  p_result_jsonb JSONB DEFAULT NULL,
  p_completed_at TIMESTAMPTZ DEFAULT NULL
)
RETURNS TABLE (applied BOOLEAN, new_version INTEGER)
LANGUAGE plpgsql
AS $$
DECLARE
  v_next_version INTEGER;
BEGIN
  UPDATE dna_memory.blackboard_steps
  SET
    status = COALESCE(p_status, status),
    claimed_by_agent_id = COALESCE(p_claimed_by_agent_id, claimed_by_agent_id),
    lock_token = p_lock_token,
    lock_expires_at = p_lock_expires_at,
    result_jsonb = COALESCE(p_result_jsonb, result_jsonb),
    completed_at = p_completed_at,
    version = version + 1,
    updated_at = NOW()
  WHERE tenant_id = p_tenant_id
    AND user_id = p_user_id
    AND id = p_id
    AND version = p_expected_version
  RETURNING version INTO v_next_version;

  IF v_next_version IS NULL THEN
    RETURN QUERY SELECT FALSE, NULL::INTEGER;
  ELSE
    RETURN QUERY SELECT TRUE, v_next_version;
  END IF;
END;
$$;

CREATE OR REPLACE VIEW dna_memory.phase3_blackboard_overview AS
SELECT
  s.tenant_id,
  s.user_id,
  s.board_id,
  s.pathway_id,
  s.session_id,
  s.status AS board_status,
  s.created_at,
  COUNT(st.id)::bigint AS total_steps,
  COUNT(st.id) FILTER (WHERE st.status = 'PENDING'::dna_memory.blackboard_step_status)::bigint AS pending_steps,
  COUNT(st.id) FILTER (WHERE st.status IN ('CLAIMED'::dna_memory.blackboard_step_status, 'IN_PROGRESS'::dna_memory.blackboard_step_status))::bigint AS claimed_steps,
  COUNT(st.id) FILTER (WHERE st.status = 'COMPLETED'::dna_memory.blackboard_step_status)::bigint AS completed_steps
FROM dna_memory.blackboard_sessions s
LEFT JOIN dna_memory.blackboard_steps st
  ON st.tenant_id = s.tenant_id
  AND st.user_id = s.user_id
  AND st.board_id = s.board_id
GROUP BY
  s.tenant_id,
  s.user_id,
  s.board_id,
  s.pathway_id,
  s.session_id,
  s.status,
  s.created_at;
