CREATE EXTENSION IF NOT EXISTS pgcrypto;

DO $$
BEGIN
  CREATE TYPE dna_memory.claim_task_status AS ENUM ('QUEUED', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'SKIPPED');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END;
$$;

DO $$
BEGIN
  CREATE TYPE dna_memory.rlhf_rule_scope AS ENUM ('PERSONAL', 'GLOBAL');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END;
$$;

DO $$
BEGIN
  CREATE TYPE dna_memory.rlhf_resolution AS ENUM ('AUTO_APPROVED', 'STAGED');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END;
$$;

CREATE TABLE IF NOT EXISTS dna_memory.claim_check_tasks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  task_id UUID NOT NULL DEFAULT gen_random_uuid(),
  tenant_id TEXT NOT NULL,
  user_id TEXT NOT NULL,
  session_id TEXT NOT NULL,
  task_type TEXT NOT NULL,
  payload_jsonb JSONB NOT NULL DEFAULT '{}'::jsonb,
  status dna_memory.claim_task_status NOT NULL DEFAULT 'QUEUED',
  stream_id TEXT,
  attempt_count INTEGER NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
  last_error TEXT,
  available_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  started_at TIMESTAMPTZ,
  processed_at TIMESTAMPTZ,
  schema_version TEXT NOT NULL,
  version INTEGER NOT NULL DEFAULT 1 CHECK (version > 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT claim_check_tasks_pk PRIMARY KEY (tenant_id, user_id, id),
  CONSTRAINT claim_check_tasks_task_id_unique UNIQUE (tenant_id, task_id)
) PARTITION BY LIST (tenant_id);

CREATE TABLE IF NOT EXISTS dna_memory.claim_check_tasks_p_default
  PARTITION OF dna_memory.claim_check_tasks DEFAULT;

CREATE TABLE IF NOT EXISTS dna_memory.session_activity (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  tenant_id TEXT NOT NULL,
  user_id TEXT NOT NULL,
  session_id TEXT NOT NULL,
  last_message_at TIMESTAMPTZ NOT NULL,
  last_queued_at TIMESTAMPTZ,
  schema_version TEXT NOT NULL,
  version INTEGER NOT NULL DEFAULT 1 CHECK (version > 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT session_activity_pk PRIMARY KEY (tenant_id, user_id, id),
  CONSTRAINT session_activity_unique UNIQUE (tenant_id, user_id, session_id)
) PARTITION BY LIST (tenant_id);

CREATE TABLE IF NOT EXISTS dna_memory.session_activity_p_default
  PARTITION OF dna_memory.session_activity DEFAULT;

CREATE TABLE IF NOT EXISTS dna_memory.rlhf_diff_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  tenant_id TEXT NOT NULL,
  user_id TEXT NOT NULL,
  session_id TEXT,
  rule_scope dna_memory.rlhf_rule_scope NOT NULL,
  original_output TEXT NOT NULL,
  edited_output TEXT NOT NULL,
  diff_patch TEXT NOT NULL,
  resolved_as dna_memory.rlhf_resolution NOT NULL,
  schema_version TEXT NOT NULL,
  version INTEGER NOT NULL DEFAULT 1 CHECK (version > 0),
  metadata_jsonb JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT rlhf_diff_events_pk PRIMARY KEY (tenant_id, user_id, id)
) PARTITION BY LIST (tenant_id);

CREATE TABLE IF NOT EXISTS dna_memory.rlhf_diff_events_p_default
  PARTITION OF dna_memory.rlhf_diff_events DEFAULT;

CREATE INDEX IF NOT EXISTS claim_check_tasks_default_status_available_idx
  ON dna_memory.claim_check_tasks_p_default (status, available_at ASC);
CREATE INDEX IF NOT EXISTS claim_check_tasks_default_session_idx
  ON dna_memory.claim_check_tasks_p_default (session_id, created_at DESC);

CREATE INDEX IF NOT EXISTS session_activity_default_idle_idx
  ON dna_memory.session_activity_p_default (last_message_at ASC, last_queued_at ASC NULLS FIRST);
CREATE INDEX IF NOT EXISTS session_activity_default_session_idx
  ON dna_memory.session_activity_p_default (session_id);

CREATE INDEX IF NOT EXISTS rlhf_diff_events_default_created_idx
  ON dna_memory.rlhf_diff_events_p_default (created_at DESC);
CREATE INDEX IF NOT EXISTS rlhf_diff_events_default_scope_idx
  ON dna_memory.rlhf_diff_events_p_default (rule_scope, created_at DESC);

DROP TRIGGER IF EXISTS trg_claim_check_tasks_touch_updated_at ON dna_memory.claim_check_tasks;
CREATE TRIGGER trg_claim_check_tasks_touch_updated_at
BEFORE UPDATE ON dna_memory.claim_check_tasks
FOR EACH ROW
EXECUTE FUNCTION dna_memory.touch_updated_at();

DROP TRIGGER IF EXISTS trg_session_activity_touch_updated_at ON dna_memory.session_activity;
CREATE TRIGGER trg_session_activity_touch_updated_at
BEFORE UPDATE ON dna_memory.session_activity
FOR EACH ROW
EXECUTE FUNCTION dna_memory.touch_updated_at();

DROP TRIGGER IF EXISTS trg_rlhf_diff_events_touch_updated_at ON dna_memory.rlhf_diff_events;
CREATE TRIGGER trg_rlhf_diff_events_touch_updated_at
BEFORE UPDATE ON dna_memory.rlhf_diff_events
FOR EACH ROW
EXECUTE FUNCTION dna_memory.touch_updated_at();

ALTER TABLE dna_memory.claim_check_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE dna_memory.session_activity ENABLE ROW LEVEL SECURITY;
ALTER TABLE dna_memory.rlhf_diff_events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS claim_check_tasks_isolation ON dna_memory.claim_check_tasks;
CREATE POLICY claim_check_tasks_isolation
ON dna_memory.claim_check_tasks
USING (
  tenant_id = current_setting('app.tenant_id', true)
  AND user_id = current_setting('app.user_id', true)
)
WITH CHECK (
  tenant_id = current_setting('app.tenant_id', true)
  AND user_id = current_setting('app.user_id', true)
);

DROP POLICY IF EXISTS session_activity_isolation ON dna_memory.session_activity;
CREATE POLICY session_activity_isolation
ON dna_memory.session_activity
USING (
  tenant_id = current_setting('app.tenant_id', true)
  AND user_id = current_setting('app.user_id', true)
)
WITH CHECK (
  tenant_id = current_setting('app.tenant_id', true)
  AND user_id = current_setting('app.user_id', true)
);

DROP POLICY IF EXISTS rlhf_diff_events_isolation ON dna_memory.rlhf_diff_events;
CREATE POLICY rlhf_diff_events_isolation
ON dna_memory.rlhf_diff_events
USING (
  tenant_id = current_setting('app.tenant_id', true)
  AND user_id = current_setting('app.user_id', true)
)
WITH CHECK (
  tenant_id = current_setting('app.tenant_id', true)
  AND user_id = current_setting('app.user_id', true)
);

CREATE OR REPLACE FUNCTION dna_memory.ensure_phase2_partition_for_subject(
  p_tenant_id TEXT,
  p_user_id TEXT
)
RETURNS TABLE (
  claim_tasks_partition TEXT,
  session_activity_partition TEXT,
  rlhf_diff_partition TEXT
)
LANGUAGE plpgsql
AS $$
DECLARE
  suffix TEXT;
  claim_name TEXT;
  session_name TEXT;
  diff_name TEXT;
BEGIN
  IF trim(COALESCE(p_tenant_id, '')) = '' OR trim(COALESCE(p_user_id, '')) = '' THEN
    RAISE EXCEPTION 'tenant_id and user_id must be non-empty for phase2 partition provisioning';
  END IF;

  suffix := dna_memory.partition_suffix(p_tenant_id, p_user_id);
  claim_name := format('claim_check_tasks_p_%s', suffix);
  session_name := format('session_activity_p_%s', suffix);
  diff_name := format('rlhf_diff_events_p_%s', suffix);

  IF to_regclass(format('dna_memory.%I', claim_name)) IS NULL THEN
    EXECUTE format(
      'CREATE TABLE dna_memory.%I PARTITION OF dna_memory.claim_check_tasks FOR VALUES IN (%L)',
      claim_name,
      p_tenant_id
    );
  END IF;

  IF to_regclass(format('dna_memory.%I', session_name)) IS NULL THEN
    EXECUTE format(
      'CREATE TABLE dna_memory.%I PARTITION OF dna_memory.session_activity FOR VALUES IN (%L)',
      session_name,
      p_tenant_id
    );
  END IF;

  IF to_regclass(format('dna_memory.%I', diff_name)) IS NULL THEN
    EXECUTE format(
      'CREATE TABLE dna_memory.%I PARTITION OF dna_memory.rlhf_diff_events FOR VALUES IN (%L)',
      diff_name,
      p_tenant_id
    );
  END IF;

  EXECUTE format(
    'CREATE INDEX IF NOT EXISTS %I ON dna_memory.%I (status, available_at ASC)',
    format('%s_status_available_idx', claim_name),
    claim_name
  );

  EXECUTE format(
    'CREATE INDEX IF NOT EXISTS %I ON dna_memory.%I (session_id, created_at DESC)',
    format('%s_session_created_idx', claim_name),
    claim_name
  );

  EXECUTE format(
    'CREATE INDEX IF NOT EXISTS %I ON dna_memory.%I (last_message_at ASC, last_queued_at ASC NULLS FIRST)',
    format('%s_idle_idx', session_name),
    session_name
  );

  EXECUTE format(
    'CREATE INDEX IF NOT EXISTS %I ON dna_memory.%I (rule_scope, created_at DESC)',
    format('%s_scope_created_idx', diff_name),
    diff_name
  );

  RETURN QUERY SELECT claim_name, session_name, diff_name;
END;
$$;

CREATE OR REPLACE FUNCTION dna_memory.update_claim_check_task_status_occ(
  p_tenant_id TEXT,
  p_user_id TEXT,
  p_task_id UUID,
  p_expected_version INTEGER,
  p_status dna_memory.claim_task_status,
  p_stream_id TEXT DEFAULT NULL,
  p_error TEXT DEFAULT NULL,
  p_started_at TIMESTAMPTZ DEFAULT NULL,
  p_processed_at TIMESTAMPTZ DEFAULT NULL,
  p_attempt_increment INTEGER DEFAULT 0
)
RETURNS TABLE (applied BOOLEAN, new_version INTEGER)
LANGUAGE plpgsql
AS $$
DECLARE
  v_next_version INTEGER;
BEGIN
  UPDATE dna_memory.claim_check_tasks
  SET
    status = p_status,
    stream_id = COALESCE(p_stream_id, stream_id),
    last_error = p_error,
    started_at = COALESCE(p_started_at, started_at),
    processed_at = COALESCE(p_processed_at, processed_at),
    attempt_count = attempt_count + GREATEST(0, p_attempt_increment),
    version = version + 1,
    updated_at = NOW()
  WHERE tenant_id = p_tenant_id
    AND user_id = p_user_id
    AND task_id = p_task_id
    AND version = p_expected_version
  RETURNING version INTO v_next_version;

  IF v_next_version IS NULL THEN
    RETURN QUERY SELECT FALSE, NULL::INTEGER;
  ELSE
    RETURN QUERY SELECT TRUE, v_next_version;
  END IF;
END;
$$;

CREATE OR REPLACE VIEW dna_memory.phase2_queue_backlog AS
SELECT
  tenant_id,
  user_id,
  status,
  COUNT(*)::bigint AS queued_items,
  MIN(created_at) AS oldest_created_at,
  MAX(created_at) AS newest_created_at
FROM dna_memory.claim_check_tasks
GROUP BY tenant_id, user_id, status;
